#Requete n°1

PREFIX frapo: <http://purl.org/cerif/frapo/>

Select  ?zone_geographique, ?annee
Where {	?x frapo:BudgetedAmount ?valeur;
     frapo:hasLocation ?zone_geographique;
     frapo:hasDeliveryDate ?annee
		FILTER(?valeur > 25 000)}



#Requete n°2
PREFIX frapo: <http://purl.org/cerif/frapo/>

Select distinct ?zone_geographique
Where {	?x frapo:BudgetedAmount  ?valeur;
     frapo:hasLocation ?zone_geographique;
     frapo:hasDeliveryDate ?annee
     FILTER(annee = 2010)} Limit 5
Order by ?valeur
