#Requete n°1
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ns: <http://example.org/ns#>

Select  ?zone_geo ?annee ?type
Where { ?x frapo:BudgetedAmount ?valeur;
         frapo:hasDeliveryDate ?annee;
         dbo:Place ?place;
         ns:hasStaff ?pers.
      ?place frapo:hasLocation ?zone_geo.
      ?pers frapo:BudgetInformation ?type.
    FILTER(?valeur > 25000)}
ORDER BY ?annee


#Requete n°2
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

Select DISTINCT ?zone_geo
Where { ?x frapo:BudgetedAmount  ?valeur;
           frapo:hasDeliveryDate ?annee;
         dbo:Place ?place.
      ?place frapo:hasLocation ?zone_geo.
      FILTER(?annee = "2010"^^xsd:gYear && ?zone_geo != "France")}
ORDER BY DESC(?valeur)
LIMIT 5


#Requetes d'étude du csv

SELECT DISTINCT ?zone ?code
Where {	?x dbo:Place ?place.
		OPTIONAL{?place frapo:hasCode ?code;
     		frapo:hasLocation ?zone.}}
ORDER BY ?code


SELECT DISTINCT ?indicateur ?code
Where {	?x ns:hasIndicator ?ind.
  		OPTIONAL{?ind frapo:hasCode ?code;
     		 frapo:BudgetInformation ?indicateur.}}
ORDER BY ?code


SELECT DISTINCT ?personnel ?code
Where {	?x ns:hasStaff ?pers.
  		OPTIONAL{?pers frapo:hasCode ?code;
     		 frapo:BudgetInformation ?personnel.}}
ORDER BY ?code

SELECT DISTINCT ?intensite ?code
Where {	?x ns:hasIntensity ?int.
  		OPTIONAL{?int frapo:hasCode ?code;
     		 frapo:BudgetInformation ?intensite.}}
ORDER BY ?code


SELECT DISTINCT ?secret
Where {	?x a frapo:Funding
		OPTIONAL{?x ns:hasSecret ?secret}}


SELECT DISTINCT ?non_disp
Where {	?x a frapo:Funding
		OPTIONAL{?x ns:notAvailable ?non_disp}}


SELECT DISTINCT ?etat_data
Where {	?x a frapo:Funding
		OPTIONAL{?x ns:hasDataState ?etat_data}}


SELECT DISTINCT ?valeur
Where {	?x a frapo:Funding
		OPTIONAL{?x frapo:BudgetedAmount ?valeur}}
ORDER BY ?valeur


#Requêtes sur plusieurs datasets

PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

Select DISTINCT ?zoneGeo ?annee (SUM(?valeur) as ?sum) (SUM(?otherValeur1) as ?otherSum1)
Where { 
  ?funding a frapo:Funding;
            frapo:BudgetedAmount ?valeur;
          frapo:hasDeliveryDate ?annee;
          dbo:Place ?place.

  ?place frapo:hasCode ?codeReg;
      frapo:hasLocation ?zoneGeo.

  ?codeReg owl:sameAs ?otherCodeReg1.

  SERVICE <http://localhost:3030/OtherSet1> {
  ?otherFunding a frapo:Funding;
                frapo:BudgetedAmount ?otherValeur1;
                dbo:year ?annee1;
                dbo:code ?otherCodeReg1.
  }
  FILTER(?annee = ?annee1)
}
GROUP BY ?zoneGeo ?annee
ORDER BY ?annee ?zoneGeo
LIMIT 10