#Requete n°1
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>

Select  ?zone_geo ?annee ?type
Where {	?x frapo:BudgetedAmount ?valeur;
     	   frapo:hasDeliveryDate ?annee;
     	   dbo:Place ?place;
     	   ex:personnel ?pers.
    	?place frapo:hasLocation ?zone_geo.
    	?pers ex:typePersonnel ?type.
		FILTER(?valeur > 25000)}
ORDER BY ?annee


#Requete n°2
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

Select DISTINCT ?zone_geo
Where {	?x frapo:BudgetedAmount  ?valeur;
           frapo:hasDeliveryDate ?annee;
     	   dbo:Place ?place.
     	?place frapo:hasLocation ?zone_geo.
     	FILTER(?annee = "2010"^^xsd:gYear)}
ORDER BY DESC(?valeur)
LIMIT 5

#Requetes d'étude du csv

SELECT DISTINCT ?zone ?code
Where {	?x dbo:Place ?place.
		OPTIONAL{?place frapo:hasCode ?code;
     		frapo:hasLocation ?zone.}}
ORDER BY ?code


SELECT DISTINCT ?indicateur ?code
Where {	?x ex:indicateur ?ind.
  		OPTIONAL{?ind frapo:hasCode ?code;
     		 ex:typeIndic ?indicateur.}}
ORDER BY ?code


SELECT DISTINCT ?personnel ?code
Where {	?x ex:personnel ?pers.
  		OPTIONAL{?pers frapo:hasCode ?code;
     		 ex:typePersonnel ?personnel.}}
ORDER BY ?code

SELECT DISTINCT ?intensite ?code
Where {	?x ex:intensite ?int.
  		OPTIONAL{?int frapo:hasCode ?code;
     		 ex:typeIntensite ?intensite.}}
ORDER BY ?code


SELECT DISTINCT ?secret
Where {	?x a frapo:Funding
		OPTIONAL{?x ex:Secret ?secret}}


SELECT DISTINCT ?non_disp
Where {	?x a frapo:Funding
		OPTIONAL{?x ex:nonDisponible ?non_disp}}


SELECT DISTINCT ?etat_data
Where {	?x a frapo:Funding
		OPTIONAL{?x ex:etatDonnee ?etat_data}}


SELECT DISTINCT ?valeur
Where {	?x a frapo:Funding
		OPTIONAL{?x frapo:BudgetedAmount ?valeur}}
ORDER BY ?valeur


#Requêtes sur un autre dataset


PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


Select DISTINCT ?zoneGeo (SUM(?valeur) as ?sum) (SUM(?otherValeur1) as ?otherSum1) (SUM(?otherValeur2) as ?otherSum2) 
Where {	
  			?funding a frapo:Funding;
              		frapo:BudgetedAmount ?valeur;
       				dbo:Place ?place.

    		?place frapo:hasCode ?codeReg;
    				frapo:hasLocation ?zoneGeo.

  			?codeReg owl:sameAs ?otherCodeReg1;
  					owl:sameAs ?otherCodeReg2.

  		SERVICE <http://localhost:3030/OtherSet1> {
			?otherFunding a frapo:Funding;
                 		frapo:BudgetedAmount ?otherValeur1;
    					dbo:code ?otherCodeReg1.
		}
		SERVICE <http://localhost:3030/OtherSet2> {
			?otherFunding a frapo:Funding;
                 		frapo:BudgetedAmount ?otherValeur2;
    					dbo:code ?otherCodeReg2.
		}
}
GROUP BY ?zoneGeo







BMa






